import type { Metadata } from "next";
import "./globals.css";
import Providers from "@/components/Providers";

export const metadata: Metadata = {
	title: "Better Auth | Neon Tech | Prisma ORM | NextJS Learning Application",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="cs">
			<body className={`antialiased`}>
				<Providers>{children}</Providers>
			</body>
		</html>
	);
}
